import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WallProvider } from "./providers/wallprovider";
import { AsyncProvider } from "./providers/asyncprovider";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AsyncProvider>
          <WallProvider>
            <div className="min-h-screen bg-gradient-to-br from-blue-400 via-cyan-500 to-indigo-600">
              <Navbar/>{children}
            </div>
          </WallProvider>
        </AsyncProvider>
      </body>
    </html>
);
}
